name: Run Mirakl to Google Sheets

on:
  schedule:
    - cron: '0 8 * * *'  # Dagelijks om 08:00 UTC
  workflow_dispatch:      # Handmatig triggeren

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          GOOGLE_SHEETS_CREDS: ${{ secrets.GOOGLE_SHEETS_CREDS }}
          MIRAKL_API_KEY: ${{ secrets.MIRAKL_API_KEY }}
        run: python main.py
